public class Main {
    public static void main(String[] args) {
        System.out.println("Переменные");
        System.out.println("Задача №1");
        var dog = 8.0;
        var cat = 3.6;
        var paper = 763789;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("Задача №2");
        dog = dog + 4;
        cat = cat + 4;
        paper = paper + 4;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("Задача №3");
        dog = dog - 3.5;
        cat = cat - 1.6;
        paper = paper - 7639;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("Задача №4");
        var friend = 12;
        System.out.println(friend);
        friend = friend + 2;
        System.out.println(friend);
        friend = friend / 7;
        System.out.println(friend);
        System.out.println("Задача №5");
        var frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog / 3.5;
        System.out.println(frog);
        frog = frog + 4;
        System.out.println(frog);
        System.out.println("Задача №6");
        var boxer1 = 78.2;
        var boxer2 = 82.7;
        System.out.println("Вес боксера №1 " + boxer1 + " кг");
        System.out.println("Вес боксера №2 " + boxer2 + " кг");
        var totalWeight = boxer1 + boxer2;
        System.out.println("Общий вес боксеров " + totalWeight + " кг");
        var weightDiff = boxer2 - boxer1;
        System.out.println("Разница в весе " + weightDiff + " кг");
        System.out.println("Задача №7");
        var weightDif = boxer2 - boxer1;
        System.out.println("Разница в весе " + weightDif + " кг");
        var weight_Dif = boxer2 % boxer1;
        System.out.println("Весовая разница " + weight_Dif + " кг");
        System.out.println("Задача №8");
        var totalTime = 640;
        var workerTime = 8;
        var allWorkers = totalTime / workerTime;
        System.out.println("Всего работников в компании - " + allWorkers + " человек");
        allWorkers = allWorkers + 94;
        workerTime = totalTime / allWorkers;
        System.out.println("Если в компании работает - " + allWorkers + " человека, то всего " + workerTime + " часа работы может быть поделено между сотрудниками");
    }
}